set number
set relativenumber
set termguicolors
set autoindent
set tabstop=4
set shiftwidth=4
set smarttab
set softtabstop=4
set mouse=a
set clipboard=unnamedplus
set autochdir
set splitbelow
set splitright
set ruler
set background=dark
set showtabline=2
set updatetime=300
set timeoutlen=300
set fileencoding=utf-8
set cursorline
colorscheme ayu
set completeopt=longest,menuone
